jube-train-juelich-booster:
	jube run jube_training.yaml -t jwb jnvidia 

jube-split-juelich:
	jube run jube_training.yaml -t jwb jnvidia split  

jube-test-split-juelich:
	jube run jube_training.yaml -t jwb jnvidia split  
