jube-split-juelich-test:
	jube run jube_training.yaml -t jwb jnvidia split test

jube-split-juelich-datamedium-test:
	jube run jube_training.yaml -t jwb jnvidia split test datamedium

jube-split-juelich-datalarge-test:
	jube run jube_training.yaml -t jwb jnvidia split test datalarge

jube-train-juelich-booster-test:
	jube run jube_training.yaml -t jwb jnvidia test

jube-train-juelich-booster-benchs-test:
	jube run jube_training.yaml -t jwb jnvidia test benchs

jube-train-juelich-h100-datamedium-test:
	jube run jube_training.yaml -t jwb h100 test datamedium

jube-train-juelich-h100-datamedium-test-double:
	jube run jube_training.yaml -t jwb h100 test datamedium gpudouble

jube-train-juelich-h100-datamedium-test-single:
	jube run jube_training.yaml -t jwb h100 test datamedium gpusingle

jube-train-juelich-mi250-datamedium:
	jube run jube_training.yaml -t jwb mi250 datamedium

jube-train-juelich-mi250-datamedium-quadro:
	jube run jube_training.yaml -t jwb mi250 datamedium gpuquadro

jube-train-juelich-mi250-datamedium-double:
	jube run jube_training.yaml -t jwb mi250 datamedium gpudouble

jube-train-juelich-booster-datamedium-test:
	jube run jube_training.yaml -t jwb jnvidia test datamedium

jube-train-juelich-booster-datamedium-test-double:
	jube run jube_training.yaml -t jwb jnvidia test datamedium gpudouble

jube-train-juelich-booster-datamedium-test-single:
	jube run jube_training.yaml -t jwb jnvidia test datamedium gpusingle

jube-train-juelich-booster-datamedium-benchs-test:
	jube run jube_training.yaml -t jwb jnvidia test datamedium benchs

jube-train-juelich-booster-datalarge-test:
	jube run jube_training.yaml -t jwb jnvidia test datalarge



jube-train-juelich-a100-datamedium-quadro:
	jube run jube_training.yaml -t jwb a100 datamedium gpuquadro


jube-split-e4-datamedium-test:
	jube run jube_training.yaml -t test split e4 datamedium gracehopper

jube-train-e4-datamedium-test:
	jube run jube_training.yaml -t test e4power e4 datamedium gracehopper

jube-train-e4-gpua2-datamedium-apptainer-test:
	jube run jube_training.yaml -t test e4power e4 datamedium apptainer gpua2

jube-train-e4-gpua2-datamedium-conda-test:
	jube run jube_training.yaml -t test e4power e4 datamedium conda gpua2

jube-train-e4-gpua2-datamedium-conda-test-single:
	jube run jube_training.yaml -t test e4power e4 datamedium conda gpua2 gpusingle
