jube-split-juelich-test:
	jube run jube_training.yaml -t jwb jnvidia split test

jube-split-juelich-datamedium-test:
	jube run jube_training.yaml -t jwb jnvidia split test datamedium

jube-split-juelich-datalarge-test:
	jube run jube_training.yaml -t jwb jnvidia split test datalarge

jube-train-juelich-booster-test:
	jube run jube_training.yaml -t jwb jnvidia test

jube-train-juelich-booster-benchs-test:
	jube run jube_training.yaml -t jwb jnvidia test benchs

jube-train-juelich-h100-datamedium-test:
	jube run jube_training.yaml -t jwb h100 test datamedium

jube-train-juelich-mi250-datamedium:
	jube run jube_training.yaml -t jwb mi250 datamedium

jube-train-juelich-booster-datamedium-test:
	jube run jube_training.yaml -t jwb jnvidia test datamedium

jube-train-juelich-booster-datamedium-benchs-test:
	jube run jube_training.yaml -t jwb jnvidia test datamedium benchs

jube-train-juelich-booster-datalarge-test:
	jube run jube_training.yaml -t jwb jnvidia test datalarge



jube-split-e4-datamedium-test:
	jube run jube_training.yaml -t test split e4 datamedium gracehopper

jube-train-e4-datamedium-test:
	jube run jube_training.yaml -t test e4 datamedium gracehopper
