UnicoreApiUrl: https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core
Environment:
  Apptainer:
    Path: /p/project/deepacf/maelstrom/ehlert1/apptainer_images/a2-cuda.sif
    Type: remote
    Options:
      - --nv
  Variables:
    GIT_PYTHON_REFRESH: quiet
Resources:
  Queue: develbooster
  Nodes: 1
  Runtime: 2h
Exclude:
  - "*.sif"
  - "figures/"
  - "saved_model"
  - README.md