UnicoreApiUrl: https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core
Environment:
  Modules:
    - cuDNN/8.6.0.163-CUDA-11.7
  PreRunCommandOnComputeNode: |
    conda activate a2py3p10
    module load Stages/2023
    module load cuDNN/8.6.0.163-CUDA-11.7
    module unload Python/3.10.4
  Python: /p/project/deepacf/maelstrom/ehlert1/deep500/empty
  Variables:
    GIT_PYTHON_REFRESH: quiet
Resources:
  Queue: develbooster
  Nodes: 1
  Runtime: 2h
Exclude:
  - "*.sif"
  - "figures/"
  - "saved_model"
  - README.md